version: "3.9"

networks:
  wp:
    driver: "bridge"

services:
  #PHP-FPM service
  app:
    build:
      context: .
      dockerfile: ./docker-files/php/Dockerfile
    container_name: wp-web-crawler
    restart: unless-stopped
    tty: true
    working_dir: /var/www/wp-web-crawler

    volumes:
      - ./:/var/www/wp-web-crawler
      - ./docker-files/php/local.ini:/usr/local/etc/php/conf.d/local.ini

    networks:
      - wp

  #   #NGINX service
  wp_webserver:
    build:
      context: .
      dockerfile: ./docker-files/nginx/Dockerfile
    container_name: wp_webserver
    restart: unless-stopped
    depends_on:
      - db
      - app

    ports:
      - "7005:80"

    volumes:
      - ./:/var/www/wp-web-crawler
      - ./docker-files/nginx/conf.d/app.conf:/etc/nginx/conf.d/app.conf

    networks:
      - wp

  db:
    container_name: wp_db
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    restart: always
    tty: true
    ports:
      - "7001:3306"

    volumes:
      - ./storage/dbdata:/var/lib/mysql
      - ./docker-files/mysql/mysql.cnf:/etc/mysql/mysql.cnf
    networks:
      - wp

  # setup db management interface
  adminer:
    container_name: wp_adminer
    image: adminer:latest
    restart: always
    ports:
      - "7002:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - wp
